name: Main workflow

on:
  - push
  - pull_request

jobs:
  create_draft_release:
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_draft_release.outputs.upload_url }}

    steps:
      - name: Create draft release on tags
        id: create_draft_release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

  build:
    needs: create_draft_release

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-18.04
          - windows-latest
        ocaml-version:
          - 4.11.1
        include:
          - os: macos-latest
            suffix: x86_64-apple-darwin
          - os: ubuntu-18.04
            ocaml-version: 4.11.1
            suffix: x86_64-unknown-linux-gnu
          - os: ubuntu-20.04
            ocaml-version: 4.11.1+musl+static+flambda
            suffix: x86_64-unknown-linux-musl
          - os: windows-latest
            suffix: x86_64-pc-windows-gnu
            stdlib_path: D:\a\caramel\caramel\_build\default\src\stdlib

    env:
      OCAML_VERSION: ${{ matrix.ocaml-version }}
      OS: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cached Infra
        uses: actions/cache@v2
        env:
          cache-name: cached-opam
        with:
          path: |
           ~/.opam
           _build
           C:\cygwin
           D:\a\caramel\caramel
          key: v${{ secrets.CACHE_VERSION }}-${{ matrix.os }}-${{ matrix.ocaml-version }}-${{ env.cache-name }}-${{ hashFiles('**/*.opam*') }}
          restore-keys: |
            v${{ secrets.CACHE_VERSION }}-{{ matrix.os }}-${{ matrix.ocaml-version }}-${{ env.cache-name }}-
            v${{ secrets.CACHE_VERSION }}-{{ matrix.os }}-${{ matrix.ocaml-version }}-
            v${{ secrets.CACHE_VERSION }}-{{ matrix.os }}-

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Set git user
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions-bot@users.noreply.github.com

      - name: Define env (unix)
        if: ${{ runner.os != 'Windows' }}
        run: echo "::set-env name=GITHUB_TAG::${GITHUB_REF#refs/*/}"

      - name: Define env (windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          $tag = "${{github.ref}}".Split("/")["${{github.ref}}".Split("/").Length -1]
          echo "::set-env name=GITHUB_TAG::$(echo $tag)"
          echo "::set-env name=CARAMELC_STDLIB_PATH::${{ matrix.stdlib_path }}"

      - name: Update Opam
        run: opam update --yes

      - name: Install dependencies
        run: opam exec -- make deps

      - name: Build project
        run: opam exec -- make clean build

      - name: Run tests
        run: opam exec -- make test

      - name: Check code formatting
        if: ${{ success() && startsWith(runner.os, 'Linux') }}
        run: opam exec -- make fmt

      - name: Create release archive
        if: ${{ success() }}
        run: |
          opam exec -- make release

      - name: Upload erlang build artifact
        if: ${{ success() && startsWith(runner.os, 'macos')}}
        uses: actions/upload-artifact@v2
        with:
          path: erlang.tbz
          name: erlang-${{ env.GITHUB_TAG }}.tbz
          if-no-files-found: error

      - name: Upload caramel build artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          path: release.tar.gz
          name: caramel-${{ env.GITHUB_TAG }}-${{ matrix.suffix }}.tar.gz
          if-no-files-found: error

      - name: Upload erlang library tarball
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') && startsWith(runner.os, 'macos')}}
        id: upload-erlang-library-tarball
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft_release.outputs.upload_url }}
          asset_path: erlang.tbz
          asset_name: erlang-${{ env.GITHUB_TAG }}.tbz
          asset_content_type: application/zip

      - name: Upload caramel release tarball
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        id: upload-caramel-release-tarball
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft_release.outputs.upload_url }}
          asset_path: release.tar.gz
          asset_name: caramel-${{ env.GITHUB_TAG }}-${{ matrix.suffix }}.tar.gz
          asset_content_type: application/zip
